### ISSUE TITLE
Document TypeScript Monorepo Usecase

### ISSUE THREAD

**Issue by dustinlacewell** [atomicpages/docusaurus-plugin-module-alias#2]
If at all possible, please document how to use this plugin to utilize TypeScript components that live within a monorepo shared with a Docusaurus site.

**Comment by atomicpages** [comment]
This plugin really passes aliases to the webpack config docusaurus use; however, with monorepos this depends on a few factors:

* the tool used to manage the monorepo
* if dependencies are hoisted to some common ancestor
* if some dependencies are _not_ hoisted

For a projected managed by lerna with hoisted modules you might do this:

```js
const path = require('path');

module.exports = {
    // ...
    plugins: [
        [
            'docusaurus-plugin-module-alias',
            {
                alias: {
                    '@local/component': path.resolve(__dirname, '../pkg-a/src/index.ts'),
                },
            },
        ],
    ],
};
```
